name: Build
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Install Haxelib
        run: |
          sudo apt-get install libvlc-dev libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hxpkg
          haxelib run hxpkg install --force
      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Install SScript from Archive
        run: |
          wget https://github.com/CobaltBar/SScript-Archive/raw/main/archives/SScript-7,0,0.zip -O SScript.zip
          haxelib install --never SScript.zip
      - name: Compile
        run: haxelib run lime build Project.xml linux --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PaperEngine-linuxBuild
          path: "export/release/linux/bin"
  buildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxpkg
          haxelib run hxpkg install --force
        shell: cmd
      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> %USERPROFILE%/settings.cocoa
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Install SScript from Archive
        run: |
          curl -Lo SScript.zip https://github.com/CobaltBar/SScript-Archive/raw/main/archives/SScript-7,0,0.zip
          haxelib install --never SScript.zip
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PaperEngine-windowsBuild
          path: export/release/windows/bin
  buildMac:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxpkg
          haxelib run hxpkg install --force
      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Install SScript from Archive
        run: |
          wget https://github.com/CobaltBar/SScript-Archive/raw/main/archives/SScript-7,0,0.zip -O SScript.zip
          haxelib install --never SScript.zip
      - name: Compile
        run: haxelib run lime build mac --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PaperEngine-macBuild
          path: export/release/macos/bin
